deploy_version: 0.1.20
image_tag: latest

applications:
  - name: django
    image: pennlabs/penn-clubs-backend
    secret: penn-clubs
    ingress:
      hosts:
        - host: pennclubs.com
          paths: ["/api"]
    extraEnv:
      - name: DOMAIN
        value: pennclubs.com
      - name: DJANGO_SETTINGS_MODULE
        value: pennclubs.settings.production
  - name: react
    image: pennlabs/penn-clubs-frontend
    secret: penn-clubs
    ingress:
      hosts:
        - host: pennclubs.com
          paths: ["/"]
    extraEnv:
      - name: PORT
        value: 80
      - name: DOMAIN
        value: pennclubs.com
  - name: websocket
    image: pennlabs/penn-clubs-websocket
    secret: penn-clubs
    ingress:
      hosts:
        - host: ws01.pennclubs.com
      extraEnv:
        - name: PORT
          value: 80
        - name: DOMAIN
          value: ws01.pennclubs.com
